<a href="https://colab.research.google.com/github/Aslan934/python_practice_datacube/blob/main/3_Practice_Numpy_Aslan_Rustamov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### 1. Numpy kitabxanasını np kimi yukleyin  və versiyasını yoxlayın

In [ ]:
### 2. 0-dan 9-a qədər olan rəqəmlərdən ibarət 1D array yaradın. (Numpy kitaxanasini  arange adin bir method var onun kömeyi ile)
import numpy as np

a=np.arange(0,9)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
### 3. 3×3 ölçülü, bütün elementləri True olan bir array  yaradın.

true_array=np.ones((3,3),dtype=bool)
true_array


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
### 4 Verilmiş array-da bütün tək rəqəmləri çıxarın.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_arr=arr[arr%2==1]
odd_arr

array([1, 3, 5, 7, 9])

In [ ]:
### 4 Tək rəqəmləri -1 ilə əvəz edin

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
### 5 Verilmiş array-dan yalnız müsbət və cüt rəqəmləri çıxarın, nəticəni tərsinə çevirərək ekrana göstərin.
arr = np.array([-10, -2, 0, 3, 4, 8, 15, -5, 12, 20])

reversed_even_positive_nums=arr[(arr>0)  & (arr%2==0)][::-1]
reversed_even_positive_nums


array([20, 12,  8,  4])

In [ ]:
### 6 Verilmiş array-dan  yalnız cüt indekslərdə yerləşən elementləri çıxarın və onların cəmini hesablayın.


arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])

new_arr=arr[::2]
print(new_arr)

sum_new_arr=new_arr.sum()
print(sum_new_arr)


[ 1  5  9 13]
28


In [ ]:
### 7  1-dən 20-yə qədər rəqəmlərdən ibarət array yaradın, sonra yalnız 5-ə və ya 7-yə bölünən rəqəmləri saxlayaraq yeni massiv yaradın.

arr = np.arange(1, 21)
filtered = arr[(arr % 5 == 0) | (arr % 7 == 0)]
print(filtered)
# Çıxış: [ 5  7 10 14 15 20]


[ 5  7 10 14 15 20]
